#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 16 11:13:08 2018

@author: alex
"""
## Boilerplate code, to be refactored.

import matplotlib.pyplot as plt
from PIL import Image
from io import BytesIO
import requests

subscription_key = ""
assert subscription_key

search_url = "https://api.cognitive.microsoft.com/bing/v7.0/images/search"
search_term = "snow on road"

headers = {"Ocp-Apim-Subscription-Key" : subscription_key}
params  = {"q": search_term, "license": "public", "imageType": "photo"}
response = requests.get(search_url, headers=headers, params=params)
response.raise_for_status()
search_results = response.json()

thumbnail_urls = [img["thumbnailUrl"] for img in search_results["value"][:16]]

f, axes = plt.subplots(4, 4)
for i in range(4):
    for j in range(4):
        image_data = requests.get(thumbnail_urls[i+4*j])
        image_data.raise_for_status()
        image = Image.open(BytesIO(image_data.content))        
        axes[i][j].imshow(image)
        axes[i][j].axis("off")

