#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 16 11:13:08 2018

@author: alex
"""

from PIL import Image
from io import BytesIO
import requests

# I should probably subclass these ¯\_(ツ)_/¯ 
class BingSearcher():
    def __init__(self, api_key, data_root, api_secret=None):
        self.rest_url = 'https://api.cognitive.microsoft.com/bing/v7.0/images/search'
        self.key = api_key
        self.data_root = data_root
    
    def download_images(self, query, page, search_grouping):
        headers = {"Ocp-Apim-Subscription-Key" : self.key}
        params  = {"q": query, "license": "public", "imageType": "photo"}

        response = requests.get(self.rest_url, headers=headers, params=params)
        search_results = response.json()

if __name__ == '__main__':
    DATA_ROOT = '/home/alex/Documents/Scripts/road-incidents-thesis/data/'
    API_KEY = u''
    query = "Snow on road"

    searcher = BingSearcher(API_KEY, DATA_ROOT)
    searcher.download_images(query,1, "snowy_road")
